// VedRith Knowledge Base — Nakshatra [V1.1 — Extended]
// Source: BPHS, Brihat Samhita, Muhurta Chintamani, Jataka Parijata
// All content hand-authored from classical Jyotisha references.

export interface NakshatraKnowledge {
  key: string; nameEn: string; nameKn: string; meaning: string
  description: string; deity: string; symbol: string
  ruler: string
  gana: 'Deva' | 'Manushya' | 'Rakshasa'
  yoni: string; nature: string; element: string; tree: string; animal: string; colour: string
  strengths: string[]; weaknesses: string[]
  suitableActivities: string[]; avoidActivities: string[]
  mantra: string
}

export const NAKSHATRA_KNOWLEDGE: Record<string, NakshatraKnowledge> = {
  Ashwini: {
    key:'Ashwini',nameEn:'Ashwini',nameKn:'ಅಶ್ವಿನಿ',
    meaning:'The horse-woman — named for the twin Ashwini Kumara divine physicians, born when Surya\'s consort took the form of a mare.',
    description:'The first Nakshatra. Ruled by Ketu, deity Ashwini Kumaras (divine physicians). Swift, pioneering, healing energy. Initiators with instinctive drive to help quickly.',
    deity:'Ashwini Kumaras (divine physician-twins)',symbol:'Horse\'s head / a chariot',
    ruler:'Ketu',gana:'Deva',yoni:'Horse (male)',nature:'Kshipra (quick / light)',element:'Prithvi (Earth)',
    tree:'Kuchila (Nux Vomica / Strychnos nux-vomica)',animal:'Horse',colour:'Deep red',
    strengths:['Swift decisive action and initiative','Natural healing and medical aptitude','Courage and pioneering spirit','Athletic ability and vitality','Spontaneous generosity'],
    weaknesses:['Impatience and restlessness','Tendency to start without completing','Can be impulsive and headstrong','Difficulty with slow methodical processes'],
    suitableActivities:['Starting medical treatments','Beginning journeys and travel','Sports and physical training','Vehicle-related activities','Quick decisive actions'],
    avoidActivities:['Slow methodical tasks requiring prolonged patience','Long-term fixed commitments without flexibility'],
    mantra:'ॐ अश्विनीकुमाराभ्यां नमः (Om Ashwinikumarabhyam Namah) — Salutation to the divine physician-twins who bring swift healing.',
  },
  Bharani: {
    key:'Bharani',nameEn:'Bharani',nameKn:'ಭರಣಿ',
    meaning:'The bearer — one who carries and sustains. The yoni symbol represents creation, death, and transformation.',
    description:'Ruled by Venus, deity Yama (dharmic justice). A Tikshna (fierce) Nakshatra of transformation and consequence. Carries serious, restrictive energy reserved for endings and discipline.',
    deity:'Yama (god of death and dharmic justice)',symbol:'Yoni (womb — carrier of birth and death)',
    ruler:'Venus (Shukra)',gana:'Manushya',yoni:'Elephant (female)',nature:'Ugra (fierce)',element:'Prithvi (Earth)',
    tree:'Amalaki (Amla / Indian Gooseberry)',animal:'Elephant',colour:'Red',
    strengths:['Deep capacity for transformation','Strong sense of dharma and justice','Endurance through difficulty','Creative sensual energy','Ability to face endings courageously'],
    weaknesses:['Overly serious or judgmental','Tendency toward extremes','Difficulty letting go','Can attract harsh karmic learning'],
    suitableActivities:['Concluding tasks and finishing ongoing work','Disciplinary actions and firm boundaries','Transformation and elimination activities','Intense physical exertion'],
    avoidActivities:['Starting major new ventures','Marriage ceremonies','Travel for joyous celebrations'],
    mantra:'ॐ यमाय नमः (Om Yamaya Namah) — Salutation to Yama, lord of dharmic consequences and righteous boundaries.',
  },
  Krittika: {
    key:'Krittika',nameEn:'Krittika',nameKn:'ಕೃತ್ತಿಕಾ',
    meaning:'The cutter — the Pleiades star cluster. Shears that cut away the inessential for purity and refinement.',
    description:'Ruled by the Sun, deity Agni. A purifying Nakshatra of critical discernment. Associated with fire, cooking, cutting, and purification. Foster mother of Kartikeya.',
    deity:'Agni (the fire deity)',symbol:'A razor, axe, or flame',
    ruler:'Sun (Surya)',gana:'Rakshasa',yoni:'Sheep (female)',nature:'Mishra (mixed)',element:'Prithvi (Earth)',
    tree:'Cluster Fig (Udumbara / Ficus racemosa)',animal:'Sheep',colour:'White / light pink',
    strengths:['Sharp intellect and critical discernment','Capacity for purification','Leadership and solar dignity','Ambition and nurturing capacity','Courage to cut away inessential'],
    weaknesses:['Tendency toward sharp cutting speech','Stubbornness and pride','Excessively demanding of self and others','Restlessness and aggression'],
    suitableActivities:['Purification and fire rituals (Homa/Yagna)','Cooking and sacred food preparation','Surgery and precise cutting','Agricultural burning and land clearing','Decisive leadership'],
    avoidActivities:['Activities requiring extreme gentleness','Important beginnings needing soft nurturing energy'],
    mantra:'ॐ अग्नये नमः (Om Agnaye Namah) — Salutation to Agni, the purifying fire that transforms and refines.',
  },
  Rohini: {
    key:'Rohini',nameEn:'Rohini',nameKn:'ರೋಹಿಣಿ',
    meaning:'The red one / the growing one — the reddish star Aldebaran, the Moon\'s most beloved consort in the zodiac.',
    description:'Ruled by the Moon, deity Brahma/Prajapati. The Moon\'s own and favourite Nakshatra — supremely auspicious for most important activities. Rich with fertility, beauty, and creative abundance.',
    deity:'Brahma (Prajapati — the creator)',symbol:'A chariot / a temple / an ox cart',
    ruler:'Moon (Chandra)',gana:'Manushya',yoni:'Serpent (male)',nature:'Sthira (fixed / steady)',element:'Prithvi (Earth)',
    tree:'Java Plum (Jamun / Syzygium cumini)',animal:'Serpent / Cobra',colour:'White / cream',
    strengths:['Exceptional beauty and aesthetic sense','Creative fertility and artistic gifts','Natural abundance and material prosperity','Magnetic nurturing personality','Strong emotional intelligence'],
    weaknesses:['Possessiveness and attachment','Can be indulgent or materialistic','Tendency toward jealousy','Over-idealization of beauty and pleasure'],
    suitableActivities:['Marriage and relationship ceremonies — supremely auspicious','Agricultural sowing and planting','Purchases of land, homes, valuables','Artistic creation and performance','All ceremonies requiring auspiciousness'],
    avoidActivities:['Extreme fasting or deprivation','Harsh cutting activities'],
    mantra:'ॐ प्रजापतये नमः (Om Prajapataye Namah) — Salutation to Prajapati-Brahma, the lord of creative proliferation and abundance.',
  },
  Mrigashira: {
    key:'Mrigashira',nameEn:'Mrigashira',nameKn:'ಮೃಗಶಿರ',
    meaning:'The deer\'s head — the star cluster in Orion representing the gentle, searching quality of the deer\'s gaze.',
    description:'Ruled by Mars, deity Soma (Moon as nectar-bearer). A soft Nakshatra with an eternally searching quality. Associated with travel, curiosity, and the gentle quest for beauty and knowledge.',
    deity:'Soma (the Moon as divine nectar-deity)',symbol:'A deer\'s head',
    ruler:'Mars (Mangala)',gana:'Deva',yoni:'Serpent (female)',nature:'Mridu (soft / gentle)',element:'Prithvi (Earth)',
    tree:'Khadira (Acacia catechu)',animal:'Female Serpent',colour:'Silver / grey',
    strengths:['Gentle attractive nature','Curious ever-seeking intelligence','Love of travel and exploration','Sensitivity and empathy','Natural aesthetic appreciation'],
    weaknesses:['Restlessness and difficulty settling','Indecisiveness and over-analysis','Can be timid or easily scattered','Searching without arriving'],
    suitableActivities:['Travel and exploration','Artistic and creative pursuits','Research requiring gentle curiosity','Social activities and forming friendships'],
    avoidActivities:['Activities requiring firm decisive force','Long-term unchanging routine'],
    mantra:'ॐ सोमाय नमः (Om Somaya Namah) — Salutation to Soma, the nectar of consciousness and celestial delight.',
  },
  Ardra: {
    key:'Ardra',nameEn:'Ardra',nameKn:'ಆರ್ದ್ರ',
    meaning:'The moist one / the green one — named for Rudra\'s teardrop or the rain-bearing quality of this fierce Nakshatra.',
    description:'Ruled by Rahu, deity Rudra (fierce Shiva). A Tikshna Nakshatra associated with storms, radical transformation, and the breaking of old structures. Corresponds to Betelgeuse.',
    deity:'Rudra (the howler — fierce storm-form of Shiva)',symbol:'A teardrop / a diamond',
    ruler:'Rahu',gana:'Manushya',yoni:'Dog (female)',nature:'Tikshna (sharp / fierce)',element:'Jala (Water)',
    tree:'Krishna (Long-leaved Fig or Terminalia arjuna per regional tradition)',animal:'Dog',colour:'Green / blue-green',
    strengths:['Intense mental activity and analytical power','Courage to face storms and transformation','Deep emotional intensity','Ability to break stagnation','Innovative thinking beyond conventions'],
    weaknesses:['Restlessness and turbulence','Can be destructive without purpose','Emotional volatility','Tendency toward arrogance or rebellion'],
    suitableActivities:['Clearing obstacles and overcoming enemies','Intense mental focus activities','Groundbreaking research','Rain-benefiting agriculture'],
    avoidActivities:['Marriage ceremonies and peaceful gatherings','Beginnings requiring stable gentle energy'],
    mantra:'ॐ रुद्राय नमः (Om Rudraya Namah) — Salutation to Rudra, lord of storms, transformation, and fierce liberation.',
  },
  Punarvasu: {
    key:'Punarvasu',nameEn:'Punarvasu',nameKn:'ಪುನರ್ವಸು',
    meaning:'Return of the light — Punar (again) + Vasu (goodness / light). Renewal after the storm of Ardra.',
    description:'Ruled by Jupiter, deity Aditi (mother of the gods). Punarvasu follows Ardra\'s storm — the return of light after darkness. Birthstar of Rama. Renewal, home-returning, and regeneration.',
    deity:'Aditi (the boundless cosmic mother, mother of the Adityas)',symbol:'A quiver of arrows / a house',
    ruler:'Jupiter (Guru)',gana:'Deva',yoni:'Cat (female)',nature:'Chara (movable)',element:'Jala (Water)',
    tree:'Bamboo (Vamsha / Bambusa bambos)',animal:'Female Cat',colour:'Lead-grey / silver',
    strengths:['Philosophical wisdom and spiritual insight','Ability to renew and begin again','Optimism and faith in cycles','Contentment and adaptability','Generous expansive heart'],
    weaknesses:['Too content with minimal — lack of ambition','Tendency to repeat patterns','Naivety or excessive optimism','Can wander without clear direction'],
    suitableActivities:['Returning home after a journey','Renewal of relationships and reconciliation','Beginning philosophy and spiritual studies','Agricultural work after rain'],
    avoidActivities:['Activities requiring sharp decisive action'],
    mantra:'ॐ अदित्यै नमः (Om Adityai Namah) — Salutation to Aditi, the infinite boundless cosmic mother who renews all things.',
  },
  Pushya: {
    key:'Pushya',nameEn:'Pushya',nameKn:'ಪುಷ್ಯ',
    meaning:'Nourisher / blossomer — from "push" (to nourish, strengthen). The king of Nakshatras, most universally auspicious.',
    description:'Ruled by Saturn, deity Brihaspati (Jupiter / Deva-Guru). Universally the most auspicious Nakshatra. Guru Pushya Yoga (Pushya on Thursday) is supreme for all major undertakings including gold purchase and business.',
    deity:'Brihaspati (Jupiter, the cosmic teacher and Deva-Guru)',symbol:'A cow\'s udder / a flower / a circle',
    ruler:'Saturn (Shani)',gana:'Deva',yoni:'Sheep (male)',nature:'Kshipra (quick / light)',element:'Jala (Water)',
    tree:'Palasha (Flame of the Forest / Butea monosperma)',animal:'Male Sheep',colour:'Red',
    strengths:['Exceptional nurturing and nourishing quality','Patience, discipline, methodical excellence','Deep spiritual wisdom','Natural authority and trustworthiness','Ability to sustain and maintain'],
    weaknesses:['Can be overly conservative','Tendency toward smugness','May become over-protective or possessive'],
    suitableActivities:['All important beginnings — Pushya is the king of auspicious Nakshatras','Guru Pushya Yoga: business, education, gold purchase','Sowing seeds and agriculture','Religious and spiritual initiations'],
    avoidActivities:['Marriage ceremonies — classical texts prohibit Pushya for Vivah specifically'],
    mantra:'ॐ बृहस्पतये नमः (Om Brihaspataye Namah) — Salutation to Brihaspati, the cosmic teacher who nourishes wisdom and auspicious beginnings.',
  },
  Ashlesha: {
    key:'Ashlesha',nameEn:'Ashlesha',nameKn:'ಆಶ್ಲೇಷ',
    meaning:'The embracer / the entwiner — from "ashlesh" (to coil around). The Naga (serpent) star of penetrating insight.',
    description:'Ruled by Mercury, deity Nagas. A Tikshna Nakshatra of sharp intelligence and serpentine energy. Deeply healing or destructive depending on intention. The coiling awareness that sees beneath surfaces.',
    deity:'Nagas (the divine serpents — keepers of wisdom)',symbol:'A coiled serpent / a circle',
    ruler:'Mercury (Budha)',gana:'Rakshasa',yoni:'Cat (male)',nature:'Tikshna (sharp)',element:'Jala (Water)',
    tree:'Naga Champa (Mesua ferrea / Ceylon Ironwood)',animal:'Male Cat',colour:'Blackish red',
    strengths:['Penetrating serpentine intelligence','Ability to see through appearances','Magnetic hypnotic presence','Healing knowledge of poisons and medicines','Precise strategic patience'],
    weaknesses:['Can be deceptive or manipulative','Holds grudges','Tendency toward secrecy','Emotional coldness beneath surface warmth'],
    suitableActivities:['Research into hidden matters and occult sciences','Medical practice especially toxicology','Naga Puja and serpent deity worship','Strategic patience-requiring activities'],
    avoidActivities:['Marriage ceremonies and trust-based beginnings','Activities requiring transparent open-hearted participation'],
    mantra:'ॐ नागेभ्यो नमः (Om Nagebhyo Namah) — Salutation to the Nagas, divine serpent keepers of wisdom and kundalini energy.',
  },
  Magha: {
    key:'Magha',nameEn:'Magha',nameKn:'ಮಘ',
    meaning:'The mighty / the great one — from "maha" (great). The royal throne Nakshatra of ancestral inheritance.',
    description:'Ruled by Ketu, deity Pitrus (Ancestors). Carries regal authoritative energy and deep ancestral connection. Associated with inheritance, royalty, pride, and fulfillment of karmic duties.',
    deity:'Pitrus (the Ancestors / Forefathers)',symbol:'A royal throne / a palanquin',
    ruler:'Ketu',gana:'Rakshasa',yoni:'Rat (male)',nature:'Ugra (fierce)',element:'Prithvi (Earth)',
    tree:'Banyan (Vata / Ficus benghalensis)',animal:'Male Rat',colour:'Ivory / royal white',
    strengths:['Natural authority and regal dignity','Respect for tradition and ancestral heritage','Generosity and magnanimity','Strong personal honour','Capacity to command and inspire'],
    weaknesses:['Pride, arrogance, and sense of entitlement','Attachment to status and lineage','Tendency toward prejudice','Excessively conservative'],
    suitableActivities:['Honouring ancestors (Shraddha, Pitru Tarpana)','Taking positions of authority','Royal or governmental activities','Spiritual practice connected to lineage and tradition'],
    avoidActivities:['Acts of humility or surrender','Starting ventures requiring flexible new thinking'],
    mantra:'ॐ पितृभ्यो नमः (Om Pitribhyo Namah) — Salutation to the Ancestors, the great ones whose light and karma we carry forward.',
  },
  PurvaPhalguni: {
    key:'PurvaPhalguni',nameEn:'Purva Phalguni',nameKn:'ಪೂರ್ವ ಫಲ್ಗುಣಿ',
    meaning:'The former reddish one — Phalguni relates to the fig tree; Purva = the first of the pair of creative delight.',
    description:'Ruled by Venus, deity Bhaga (marital happiness and pleasure). A soft pleasurable Nakshatra of rest, creativity, sexuality, and the fullness of enjoyment. Part of the Phalguni pair.',
    deity:'Bhaga (deity of marital happiness, fortune, and righteous pleasure)',symbol:'A swinging hammock / front legs of a bed',
    ruler:'Venus (Shukra)',gana:'Manushya',yoni:'Rat (female)',nature:'Ugra (fierce)',element:'Agni (Fire)',
    tree:'Palasha (Flame of the Forest / Butea monosperma)',animal:'Female Rat',colour:'Light brown / buff',
    strengths:['Creative artistic nature','Warm generous and affectionate','Capacity for deep enjoyment','Natural charisma and social grace','Loyalty in relationships'],
    weaknesses:['Indulgence and hedonism','Laziness or over-reliance on pleasure','Vanity and excessive concern with appearance','Difficulty with harsh conditions'],
    suitableActivities:['Creative and artistic activities','Marriage-related and romantic ceremonies','Rest, rejuvenation, and leisure','Musical performance and entertainment'],
    avoidActivities:['Austerities and strict fasting','Activities of harsh physical labour'],
    mantra:'ॐ भगाय नमः (Om Bhagaya Namah) — Salutation to Bhaga, the divine bestower of marital bliss and righteous enjoyment.',
  },
  UttaraPhalguni: {
    key:'UttaraPhalguni',nameEn:'Uttara Phalguni',nameKn:'ಉತ್ತರ ಫಲ್ಗುಣಿ',
    meaning:'The latter reddish one — Uttara = the second of the pair, carrying the harvest and mature creative fruit.',
    description:'Ruled by the Sun, deity Aryaman (contracts and friendship). Completes what Purva Phalguni began — the harvest of creative work, maturation of relationships. More grounded and responsible than its predecessor.',
    deity:'Aryaman (the Aditya of contracts, partnership, and civilisation)',symbol:'Back legs of a bed / a fig tree in full fruit',
    ruler:'Sun (Surya)',gana:'Manushya',yoni:'Cow (male)',nature:'Dhruva (fixed)',element:'Agni (Fire)',
    tree:'Peepul (Sacred Fig / Ficus religiosa)',animal:'Cow',colour:'Bright blue / sapphire',
    strengths:['Reliable responsible and steady character','Natural leadership and solar dignity','Strong ethical standards and fairness','Capacity for deep lasting commitments','Practical creativity with tangible results'],
    weaknesses:['Can be inflexible or overly formal','Tendency toward self-righteousness','May be slow to act decisively'],
    suitableActivities:['Marriage and long-term relationship ceremonies','Signing contracts and agreements','Leadership and governance activities','Projects requiring steady sustained effort'],
    avoidActivities:['Activities requiring rapid changes of direction'],
    mantra:'ॐ अर्यम्णे नमः (Om Aryamne Namah) — Salutation to Aryaman, keeper of sacred contracts, hospitality, and civilised society.',
  },
  Hasta: {
    key:'Hasta',nameEn:'Hasta',nameKn:'ಹಸ್ತ',
    meaning:'The hand — associated with skill, craft, dexterity, and the magical manifesting power of the human hand.',
    description:'Ruled by the Moon, deity Savitar (creative aspect of the Sun). A quick skilled Nakshatra of crafts, healing, and the manifesting power of dexterity. The hand that builds and heals.',
    deity:'Savitar (the Sun in its creative stimulating aspect)',symbol:'An open hand / a fist',
    ruler:'Moon (Chandra)',gana:'Deva',yoni:'Buffalo (female)',nature:'Kshipra (quick / light)',element:'Agni (Fire)',
    tree:'Hritaki (Haritaki / Terminalia chebula)',animal:'Female Buffalo',colour:'Deep green',
    strengths:['Exceptional manual dexterity and craftsmanship','Healing hands and touch-based healing','Quick intelligence and adaptability','Humour and wit','Ability to manifest ideas physically'],
    weaknesses:['Can be crafty or manipulative','Tendency toward nervousness or anxiety','May scatter across too many skills','Can be inconsistent'],
    suitableActivities:['Craft, art, sculpture, and handiwork','Healing — massage, surgery, acupressure','Precise detailed activities','Commercial activities and trade'],
    avoidActivities:['Sustained single-minded focus without variety'],
    mantra:'ॐ सवित्रे नमः (Om Savitre Namah) — Salutation to Savitar, the stimulating creative solar force that awakens skill and vitality.',
  },
  Chitra: {
    key:'Chitra',nameEn:'Chitra',nameKn:'ಚಿತ್ರ',
    meaning:'The brilliant / the shining jewel — the star Spica (Alpha Virginis), brightest gem in Virgo.',
    description:'Ruled by Mars, deity Vishwakarma (divine architect). A brilliant creative Nakshatra that seeks masterpieces of beauty. The star of visionary artists, architects, and creative masters.',
    deity:'Vishwakarma (the divine architect, craftsman, and creator of the gods)',symbol:'A bright jewel / a pearl / Spica star',
    ruler:'Mars (Mangala)',gana:'Rakshasa',yoni:'Tiger (female)',nature:'Mridu (soft)',element:'Agni (Fire)',
    tree:'Bel (Bilva / Aegle marmelos)',animal:'Female Tiger',colour:'Black / midnight blue',
    strengths:['Exceptional aesthetic vision and creative mastery','Attention to exquisite detail','Magnetic attractive personality','Natural architectural and spatial intelligence','Perfectionist drive toward beauty'],
    weaknesses:['Perfectionism leading to harsh judgment','Can be vain or preoccupied with appearances','Restlessness when creative vision is blocked','Tendency toward selfish independence'],
    suitableActivities:['All fine arts: painting, sculpture, jewellery, design','Architecture and beautiful construction','Fashion, textiles, and ornamentation','Projects requiring brilliant originality'],
    avoidActivities:['Repetitive routine tasks without creative element'],
    mantra:'ॐ विश्वकर्मणे नमः (Om Vishvakarmane Namah) — Salutation to Vishwakarma, the supreme divine craftsman who creates with intention and beauty.',
  },
  Swati: {
    key:'Swati',nameEn:'Swati',nameKn:'ಸ್ವಾತಿ',
    meaning:'The self-going / the sword — the star of independence. The free-moving wind. Corresponds to Arcturus.',
    description:'Ruled by Rahu, deity Vayu (wind god). Highly independent Nakshatra — moves as the wind, unattached and free. Associated with trade, commerce, and the entrepreneurial spirit crossing all boundaries.',
    deity:'Vayu (the wind deity — lord of breath and freedom)',symbol:'A sword / a young shoot in the wind / coral',
    ruler:'Rahu',gana:'Deva',yoni:'Buffalo (male)',nature:'Chara (movable)',element:'Agni (Fire)',
    tree:'Arjuna (Terminalia arjuna)',animal:'Male Buffalo',colour:'Black / blue-black',
    strengths:['Independence and self-reliance','Entrepreneurial instinct and commercial acumen','Flexibility and adaptability','Charitable and humanitarian impulses','Cross-cultural and global perspective'],
    weaknesses:['Difficulty with commitment and stability','Can be arrogant about independence','Tendency to scatter energy','Restlessness preventing deep roots'],
    suitableActivities:['Business, trade, and commercial ventures','Travel and cross-cultural exploration','Freedom-requiring activities','Diplomatic roles and negotiation'],
    avoidActivities:['Activities requiring long-term rooted stability','Traditional highly conventional environments'],
    mantra:'ॐ वायवे नमः (Om Vayave Namah) — Salutation to Vayu, the life-giving wind that sustains all beings and carries consciousness.',
  },
  Vishakha: {
    key:'Vishakha',nameEn:'Vishakha',nameKn:'ವಿಶಾಖ',
    meaning:'The forked / the star with a large branch — the forking tree that bears fruit only at its extremities.',
    description:'Ruled by Jupiter, deities Indra and Agni jointly. Intense goal-oriented energy. The star of passion, ambition, and focused purpose that does not rest until the goal is achieved.',
    deity:'Indra and Agni (sovereign power and purifying fire of purpose)',symbol:'A forked branching tree / a triumphal arch',
    ruler:'Jupiter (Guru)',gana:'Rakshasa',yoni:'Tiger (male)',nature:'Mishra (mixed)',element:'Agni (Fire)',
    tree:'Vikankata (Sacred Jujube / Feronia elephantum)',animal:'Male Tiger',colour:'Golden yellow',
    strengths:['Focused ambition and goal-directed energy','Perseverance through obstacles','Philosophical depth with practical drive','Inspiring leadership for a cause','Clarity of purpose'],
    weaknesses:['Excessive ambition and envy','Impatience with slower individuals','Can be fanatical or single-minded','Tendency toward jealousy'],
    suitableActivities:['Pursuing long-term ambitious goals','Activities requiring determination and willpower','Political or community leadership','Intense spiritual practice'],
    avoidActivities:['Activities requiring unprincipled compromise'],
    mantra:'ॐ इन्द्राग्निभ्यां नमः (Om Indragnibhyam Namah) — Salutation to Indra and Agni together — sovereign will and purifying fire.',
  },
  Anuradha: {
    key:'Anuradha',nameEn:'Anuradha',nameKn:'ಅನುರಾಧ',
    meaning:'Following success — Anu (following) + Radha (success). A Nakshatra of devoted friendship and organised achievement.',
    description:'Ruled by Saturn, deity Mitra (friendship and cooperative sun). A devoted, organised, success-oriented Nakshatra. The loyal friend and disciplined seeker — balanced between worldly success and spiritual devotion.',
    deity:'Mitra (the Aditya of friendship, pacts, and cooperative success)',symbol:'A staff of honour / a lotus',
    ruler:'Saturn (Shani)',gana:'Deva',yoni:'Deer (female)',nature:'Mridu (soft)',element:'Agni (Fire)',
    tree:'Bakul (Spanish Cherry / Mimusops elengi)',animal:'Female Deer',colour:'Reddish brown',
    strengths:['Deep capacity for friendship and loyal devotion','Disciplined organised and systematic','Spiritual aspiration with worldly capability','Cross-cultural success and foreign travel','Patience through difficult paths'],
    weaknesses:['Emotionally suppressed or repressed','Depends too much on validation','May hold excessive grudges when betrayed'],
    suitableActivities:['Building and sustaining long-term friendships','Organisation and systematic work','Sustained spiritual dedication','Work with foreign cultures or travel abroad'],
    avoidActivities:['Impulsive actions without planning'],
    mantra:'ॐ मित्राय नमः (Om Mitraya Namah) — Salutation to Mitra, the solar Aditya of friendship, covenant, and cooperative advancement.',
  },
  Jyeshtha: {
    key:'Jyeshtha',nameEn:'Jyeshtha',nameKn:'ಜ್ಯೇಷ್ಠ',
    meaning:'The eldest / the chief / the most excellent — the star of seniority, supreme authority, and regal responsibility.',
    description:'Ruled by Mercury, deity Indra (king of gods). Carries regal protective senior energy. Represents the pinnacle of worldly achievement and the weight of responsibility that comes with seniority.',
    deity:'Indra (king of the gods, lord of thunder, rain, and sovereign power)',symbol:'A circular amulet / an umbrella / earrings',
    ruler:'Mercury (Budha)',gana:'Rakshasa',yoni:'Deer (male)',nature:'Tikshna (sharp)',element:'Agni (Fire)',
    tree:'Shalmali (Silk Cotton Tree / Bombax ceiba)',animal:'Male Deer',colour:'Cream / off-white',
    strengths:['Natural authority and protective instinct','Strong mind and administrative capability','Courage in the most challenging circumstances','Deep sense of personal honour','Sharp penetrating intelligence'],
    weaknesses:['Pride and desire for superiority','Can be manipulative when threatened','Tendency toward jealousy of rivals','Tension from weight of responsibility'],
    suitableActivities:['Leadership and administrative roles','Protective actions for dependants or community','Activities requiring authority and command'],
    avoidActivities:['Situations requiring equality and peer-level cooperation'],
    mantra:'ॐ इन्द्राय नमः (Om Indraya Namah) — Salutation to Indra, sovereign lord of heaven and the protective power of righteous authority.',
  },
  Moola: {
    key:'Moola',nameEn:'Moola',nameKn:'ಮೂಲ',
    meaning:'The root / the base / the origin — aligned with the Galactic Centre of the Milky Way. The deepest origin.',
    description:'Ruled by Ketu, deity Nirriti (dissolution and the void). Intensely transformative and investigative. Digs to the very root of existence. Primal connection to the Galactic Centre.',
    deity:'Nirriti (goddess of dissolution, the void, and calamitous change)',symbol:'A bunch of roots tied together / an elephant\'s goad',
    ruler:'Ketu',gana:'Rakshasa',yoni:'Dog (male)',nature:'Tikshna (sharp)',element:'Agni (Fire)',
    tree:'Sarjaka (Sal Tree / Shorea robusta)',animal:'Male Dog',colour:'Yellow-brown / dark brown',
    strengths:['Penetrating insight into root causes','Research ability and desire for origins','Spiritual depth and primal connection','Courage to face the darkest truths','Capacity for complete transformation'],
    weaknesses:['Can cause destruction before transformation occurs','May harm family or ancestral connections','Arrogance about unique nature','Destructive when frustrated'],
    suitableActivities:['Deep research and investigation','Uprooting old limiting structures','Spiritual transformation practices','Agricultural work with roots and tubers'],
    avoidActivities:['New ventures (Moola digs up first, creates after)','Irreversible decisions at the start of Ketu dasha'],
    mantra:'ॐ निर्रित्यै नमः (Om Nirrityai Namah) — Salutation to Nirriti, who dissolves all limiting structures so the eternal root may be revealed.',
  },
  PurvaAshadha: {
    key:'PurvaAshadha',nameEn:'Purva Ashadha',nameKn:'ಪೂರ್ವ ಆಷಾಢ',
    meaning:'The earlier invincible one — the first Ashadha, associated with invincibility and water purification before the final victory.',
    description:'Ruled by Venus, deity Apas (cosmic waters). A purifying Nakshatra carrying invincibility and the transformative power of water. The refreshing energy before a great victory is complete.',
    deity:'Apas (the cosmic waters — deity of purification and oceanic cleansing)',symbol:'A fan / a winnowing basket',
    ruler:'Venus (Shukra)',gana:'Manushya',yoni:'Monkey (female)',nature:'Ugra (fierce)',element:'Jala (Water)',
    tree:'Ashoka (Saraca asoca)',animal:'Female Monkey',colour:'Black / dark brown',
    strengths:['Invincibility and stubbornness for goals','Creative artistic sensitivity','Purifying energy — cleanses and refreshes','Philosophical idealism and vision','Persuasive communication'],
    weaknesses:['Inflexibility — refuses defeat even when wrong','Can be overly philosophical and impractical','Pride in intellectual prowess','Tendency to over-plan without acting'],
    suitableActivities:['Water-related activities — swimming, sailing, water therapy','Philosophical and educational pursuits','Creative arts especially music and writing','Determination against odds'],
    avoidActivities:['Situations where surrender or compromise is necessary'],
    mantra:'ॐ अद्भ्यो नमः (Om Adbhyo Namah) — Salutation to Apas, the divine cosmic waters that purify, nourish, and carry creation.',
  },
  UttaraAshadha: {
    key:'UttaraAshadha',nameEn:'Uttara Ashadha',nameKn:'ಉತ್ತರ ಆಷಾಢ',
    meaning:'The latter invincible one — final universal victory of dharma that cannot be reversed or undone.',
    description:'Ruled by the Sun, deity Vishvedevas (ten universal gods). Completes Purva Ashadha\'s victory — universal dharmic triumph that stands permanently. The star of final, irreversible victories.',
    deity:'Vishvedevas (the ten universal deities representing all cosmic laws)',symbol:'An elephant\'s tusk / elephant',
    ruler:'Sun (Surya)',gana:'Manushya',yoni:'Mongoose (male)',nature:'Dhruva (fixed)',element:'Prithvi (Earth)',
    tree:'Jack Fruit (Panasa / Artocarpus heterophyllus)',animal:'Mongoose',colour:'Copper / golden brown',
    strengths:['Capacity for universal dharmic victory','Deep integrity and righteous duty','Leadership serving the greater good','Patience for the right moment','Strength in difficult circumstances'],
    weaknesses:['Self-righteous or overconfident in dharmic stance','Slow to adapt when flexibility is needed','Tendency toward solitude and withdrawal'],
    suitableActivities:['Completing major life projects and victories','Dharmic leadership activities','Long-term spiritual commitment','Anything serving the universal good'],
    avoidActivities:['Quick-fix solutions or shortcuts'],
    mantra:'ॐ विश्वेभ्यो देवेभ्यो नमः (Om Vishvebhyo Devebhyo Namah) — Salutation to all the Vishvedevas, universal lords of cosmic order and dharmic law.',
  },
  Shravana: {
    key:'Shravana',nameEn:'Shravana',nameKn:'ಶ್ರವಣ',
    meaning:'The listening one / the hearer — from Shravana (to hear). The Nakshatra of divine listening and sacred learning.',
    description:'Ruled by the Moon, deity Vishnu (all-pervading). Associated with sacred learning through listening, pilgrimage, and guidance from attentive receptivity. The star of shruti (that which is heard — the Vedas).',
    deity:'Vishnu (in his all-pervading, sustaining, omnipresent aspect)',symbol:'Three footprints / an ear',
    ruler:'Moon (Chandra)',gana:'Deva',yoni:'Monkey (male)',nature:'Chara (movable)',element:'Vayu (Air)',
    tree:'Arka (Calotropis procera / Crown Flower)',animal:'Male Monkey',colour:'Light blue',
    strengths:['Exceptional listening and learning ability','Broad knowledge from travel and discourse','Devotion to dharma and sacred knowledge','Sensitivity and perceptiveness','Ability to connect disparate ideas'],
    weaknesses:['Overly sensitive to gossip or negative speech','Tendency toward worry and overthinking','Absorbs others\' negativity too easily','Restlessness and frequent environmental changes'],
    suitableActivities:['Listening to discourses, music, and sacred teachings','Pilgrimage and sacred travel','Teaching and knowledge transmission','All activities on Shravana day (highly auspicious)'],
    avoidActivities:['Speaking without listening — Shravana demands receptivity'],
    mantra:'ॐ विष्णवे नमः (Om Vishnave Namah) — Salutation to Vishnu, the all-pervading sustainer whose divine message is heard by the attentive heart.',
  },
  Dhanishtha: {
    key:'Dhanishtha',nameEn:'Dhanishtha',nameKn:'ಧನಿಷ್ಠ',
    meaning:'The wealthiest / the most famous — Dhana (wealth) + ishtha (most desired). Also called Shravishtha.',
    description:'Ruled by Mars, deity Ashta Vasus (eight cosmic powers of abundance). Associated with wealth, fame, musical ability, and the power of the group. The most rhythmic Nakshatra — the star of drums and martial music.',
    deity:'Ashta Vasus (the eight elemental cosmic powers of abundance and rhythm)',symbol:'A drum / a flute / a wealth pot',
    ruler:'Mars (Mangala)',gana:'Rakshasa',yoni:'Lion (female)',nature:'Chara (movable)',element:'Vayu (Air)',
    tree:'Shami (Prosopis cineraria / Khejri tree)',animal:'Female Lion',colour:'Silver / metallic grey',
    strengths:['Natural musical ability and rhythm','Capacity for fame and recognition','Generosity and sharing of abundance','Leadership in group endeavours','Courage and martial strength'],
    weaknesses:['Materialism and attachment to wealth','Can be boastful or self-promoting','Difficulty with intimacy in relationships','Overwork in pursuit of wealth'],
    suitableActivities:['Music, performance, and rhythmic activities','Commerce and wealth-building ventures','Group coordination activities','Martial arts and physical training'],
    avoidActivities:['Marriage ceremonies — Dhanishtha is traditionally avoided for Vivah in some regions'],
    mantra:'ॐ वसुभ्यो नमः (Om Vasubhyo Namah) — Salutation to the eight Vasus, cosmic lords of abundance, rhythm, and elemental wealth.',
  },
  Shatabhisha: {
    key:'Shatabhisha',nameEn:'Shatabhisha',nameKn:'ಶತಭಿಷ',
    meaning:'The hundred healers — Shata (hundred) + Bhishaj (healer / physician). A vast star cluster in Aquarius.',
    description:'Ruled by Rahu, deity Varuna (cosmic ocean and truth). The star of mystical healing, cosmic vastness, and the hundred physicians who govern the celestial waters. Occult and scientific depth.',
    deity:'Varuna (cosmic lord of truth, celestial oceans, and cosmic law)',symbol:'An empty circle / a hundred flowers or stars',
    ruler:'Rahu',gana:'Rakshasa',yoni:'Horse (female)',nature:'Chara (movable)',element:'Vayu (Air)',
    tree:'Kadamba (Neolamarckia cadamba)',animal:'Female Horse',colour:'Blue-green / aqua',
    strengths:['Mystical and occult healing abilities','Deep philosophical and scientific mind','Independence of thought and action','Connection to cosmic transpersonal forces','Trustworthy keeper of mysteries and secrets'],
    weaknesses:['Extreme introversion and isolation','Can be eccentric or socially withdrawn','Secretiveness that becomes loneliness','Sudden inexplicable crises'],
    suitableActivities:['Medical research and healing','Occult sciences and astrology','Scientific and philosophical investigation','Deep concentration in solitude'],
    avoidActivities:['Social activities requiring continuous extroversion','Large group cooperation dependencies'],
    mantra:'ॐ वरुणाय नमः (Om Varunaya Namah) — Salutation to Varuna, the oceanic cosmic lord of truth, sacred vows, and healing celestial waters.',
  },
  PurvaBhadrapada: {
    key:'PurvaBhadrapada',nameEn:'Purva Bhadrapada',nameKn:'ಪೂರ್ವ ಭಾದ್ರಪದ',
    meaning:'The former auspicious feet — the step before the final transcendent step. Intense fiery idealism.',
    description:'Ruled by Jupiter, deity Aja Ekapada (one-footed unborn form of Rudra). Carries intense fiery transformative energy — passionate idealism that burns away the conventional in preparation for liberation.',
    deity:'Aja Ekapada (the one-footed unborn cosmic fire serpent / thunderbolt)',symbol:'A sword / two front legs of a funeral cot',
    ruler:'Jupiter (Guru)',gana:'Manushya',yoni:'Lion (male)',nature:'Ugra (fierce)',element:'Vayu (Air)',
    tree:'Neem (Azadirachta indica)',animal:'Male Lion',colour:'Silver / grey',
    strengths:['Intense passion for transformative ideals','Fearlessness in facing the unknown','Philosophical depth combined with fire','Capacity for spiritual renunciation','Sharp penetrating intellect'],
    weaknesses:['Extremism and fanatic idealism','Erratic behaviour shocking the conventional','Difficulty with emotional intimacy','Can be cynical when ideals fail'],
    suitableActivities:['Intense spiritual practices and sadhana','Research into death, transformation, hidden truths','Philosophical and occult study','Activities challenging the status quo'],
    avoidActivities:['Marriage and conventional relationship ceremonies','Consistent stable social engagement'],
    mantra:'ॐ अज एकपदाय नमः (Om Aja Ekapadaya Namah) — Salutation to Aja Ekapada, the one-footed unborn cosmic fire standing beyond conventional reality.',
  },
  UttaraBhadrapada: {
    key:'UttaraBhadrapada',nameEn:'Uttara Bhadrapada',nameKn:'ಉತ್ತರ ಭಾದ್ರಪದ',
    meaning:'The latter auspicious feet — the final step that brings one to the threshold of liberation.',
    description:'Ruled by Saturn, deity Ahir Budhnya (serpent of the cosmic depths). The most profoundly spiritual Nakshatra of Pisces — oceanic depth, wisdom from long experience, and the tranquility of a completed journey.',
    deity:'Ahir Budhnya (the serpent of the depths — cosmic primordial dragon)',symbol:'The back legs of a funeral cot / twins',
    ruler:'Saturn (Shani)',gana:'Manushya',yoni:'Cow (female)',nature:'Sthira (fixed)',element:'Vayu (Air)',
    tree:'Neem (Azadirachta indica)',animal:'Female Cow',colour:'Purple / deep blue',
    strengths:['Deep oceanic wisdom from many lifetimes','Compassion and capacity for universal love','Patience and equanimity in all circumstances','Spiritual depth and service orientation','Ability to bring peace to troubled situations'],
    weaknesses:['Excessively withdrawn or reclusive','Tendency toward melancholy when cut from spirit','Too passive when action is required'],
    suitableActivities:['Deep meditation and contemplative practice','Service to the elderly and ill','Spiritual teaching and guiding others','Water, ocean, and sacred river activities'],
    avoidActivities:['Highly competitive environments'],
    mantra:'ॐ अहिर्बुध्न्याय नमः (Om Ahirbudhnyaya Namah) — Salutation to Ahir Budhnya, the ancient cosmic dragon holding primordial wisdom of the universe.',
  },
  Revati: {
    key:'Revati',nameEn:'Revati',nameKn:'ರೇವತಿ',
    meaning:'The wealthy one / the prosperous / the guide — who leads souls safely across boundaries and transitions.',
    description:'Ruled by Mercury, deity Pushan (nourisher of travellers). The final Nakshatra — carrying conclusion, nourishment for the journey, and safe passage. The bridge between cycles and the compassionate guide at transitions.',
    deity:'Pushan (the nourisher, shepherd of souls, protector of travellers and animals)',symbol:'A fish / a drum / a pair of fish',
    ruler:'Mercury (Budha)',gana:'Deva',yoni:'Elephant (female)',nature:'Mridu (soft)',element:'Vayu (Air)',
    tree:'Mahua (Madhuca longifolia)',animal:'Female Elephant',colour:'Brown / earthy',
    strengths:['Capacity to guide and nourish through transitions','Deep compassion and protective instinct','Natural wisdom about endings and new beginnings','Gentleness and healing presence','Thrives at crossroads and transitions'],
    weaknesses:['Over-attachment to endings','Excessively nostalgic or stuck in the past','Tends to linger when moving on is necessary','May be naive or too trusting'],
    suitableActivities:['Concluding projects with grace','Travel — Pushan protects journeys','Nourishment activities — feeding others, caregiving','Transitions: moving, changing roles','Care of animals'],
    avoidActivities:['Starting aggressive long-term new ventures (Revati is completing energy)'],
    mantra:'ॐ पूष्णे नमः (Om Pushne Namah) — Salutation to Pushan, the divine nourisher who guides travellers and leads souls safely across all transitions.',
  },
}

export function getNakshatraKnowledge(key: string): NakshatraKnowledge | null {
  return NAKSHATRA_KNOWLEDGE[key] ?? null
}
