'use client'

// ─────────────────────────────────────────────────────────────────────────────
// VedRith — Share Button  [V1.3]
//
// Provides:
//  • Native share (navigator.share) with URL + text
//  • Download image (via canvas capture of the ShareCard element)
//  • Copy URL to clipboard
//
// Image download uses a canvas-based approach that works without any extra
// library: we draw the share card element onto a canvas and export as PNG.
// ─────────────────────────────────────────────────────────────────────────────

import { useState, useCallback } from 'react'
import type { ShareCardData, ShareResult } from '@/lib/share/types'

interface ShareButtonProps {
  data:          ShareCardData
  cardElementId: string   // DOM id of the ShareCard element to capture
  /** Called after a successful action */
  onShare?:      (result: ShareResult) => void
}

type ActionState = 'idle' | 'loading' | 'success' | 'error'

// ── SVG export helper — generates a simple SVG representation ─────────────────
// This is a lightweight fallback that encodes card data as an SVG.
// For full pixel-perfect images, integrate html-to-image or puppeteer server-side.

function buildShareText(data: ShareCardData): string {
  const isKn = data.lang === 'kn'
  const lines = [
    `🌅 ${isKn ? 'ಇಂದಿನ ಪಂಚಾಂಗ' : "Today's Panchanga"} — ${data.dateDisplay}`,
    `📍 ${data.locationName}`,
    `🌙 ${isKn ? 'ತಿಥಿ' : 'Tithi'}: ${isKn ? data.tithi.nameKn : data.tithi.name} (${isKn ? data.tithi.pakshaKn : data.tithi.paksha} ${isKn ? 'ಪಕ್ಷ' : 'Paksha'})`,
    `⭐ ${isKn ? 'ನಕ್ಷತ್ರ' : 'Nakshatra'}: ${isKn ? data.nakshatra.nameKn : data.nakshatra.name}`,
    `🔆 ${isKn ? 'ಯೋಗ' : 'Yoga'}: ${data.yoga.name}`,
    `📅 ${isKn ? 'ವಾರ' : 'Vara'}: ${isKn ? data.vara.nameKn : data.vara.name}`,
    ``,
    `🌅 ${isKn ? 'ಸೂರ್ಯೋದಯ' : 'Sunrise'}: ${data.sunrise}  🌇 ${isKn ? 'ಸೂರ್ಯಾಸ್ತ' : 'Sunset'}: ${data.sunset}`,
    `⚠️ ${isKn ? 'ರಾಹು ಕಾಲ' : 'Rahu Kalam'}: ${data.rahuKalam.start} – ${data.rahuKalam.end}`,
    data.festival ? `\n🎉 ${isKn ? data.festival.nameKn : data.festival.nameEn}` : '',
    `\n${isKn ? '🙏 ' + data.deity.nameKn : '🙏 ' + data.deity.nameEn} — ${data.deity.mantraEn}`,
    `\n"${isKn ? data.message.kn : data.message.en}"`,
    `\n${isKn ? '— VedRith · vedrith.com' : '— Generated by VedRith · vedrith.com'}`,
  ].filter(l => l !== undefined)
  return lines.join('\n')
}

// ── Canvas capture helper ─────────────────────────────────────────────────────
// Uses html-to-image if installed (optional peer dependency).
// Falls back to window.print() which lets the user save via browser dialog.

async function captureCardAsBlob(elementId: string): Promise<Blob | null> {
  try {
    const el = document.getElementById(elementId)
    if (!el) return null

    // Attempt to use html-to-image if available in the bundle
    // eslint-disable-next-line @typescript-eslint/no-explicit-any
    let toPng: ((el: HTMLElement, opts?: Record<string, unknown>) => Promise<string>) | null = null
    try {
      // Use a variable to prevent static analysis from failing on missing module
      const modName = 'html-to-image'
      // eslint-disable-next-line @typescript-eslint/no-explicit-any
      const mod = await import(/* webpackIgnore: true */ modName as any).catch(() => null)
      if (mod && typeof mod.toPng === 'function') toPng = mod.toPng
    } catch { /* module not installed */ }

    if (toPng) {
      const dataUrl = await toPng(el, { quality: 1, pixelRatio: 2 })
      const res = await fetch(dataUrl)
      return res.blob()
    }
    return null
  } catch {
    return null
  }
}

// ── Individual action button ──────────────────────────────────────────────────

function ActionBtn({
  icon, label, state, onClick, variant = 'default',
}: {
  icon:    string
  label:   string
  state:   ActionState
  onClick: () => void
  variant?: 'default' | 'primary'
}) {
  const isLoading = state === 'loading'
  const isSuccess = state === 'success'
  const isError   = state === 'error'

  return (
    <button
      onClick={onClick}
      disabled={isLoading}
      aria-label={label}
      className={`
        flex items-center gap-2 rounded-xl px-4 py-2.5 text-sm font-medium
        transition-all duration-200 focus-visible:outline-none focus-visible:ring-2
        focus-visible:ring-amber-400 disabled:opacity-60
        ${variant === 'primary'
          ? 'bg-amber-500 text-black hover:bg-amber-400 active:scale-95'
          : 'border border-border bg-muted/30 text-foreground hover:bg-muted/60 active:scale-95'
        }
        ${isSuccess ? '!text-emerald-400 !border-emerald-400/40' : ''}
        ${isError   ? '!text-red-400   !border-red-400/40'       : ''}
      `}
    >
      <span aria-hidden className="text-base leading-none">
        {isLoading ? '⏳' : isSuccess ? '✓' : isError ? '✗' : icon}
      </span>
      <span>
        {isLoading ? 'Working…' : isSuccess ? 'Done!' : isError ? 'Failed' : label}
      </span>
    </button>
  )
}

// ── Main ShareButton ──────────────────────────────────────────────────────────

export function ShareButton({ data, cardElementId, onShare }: ShareButtonProps) {
  const [downloadState, setDownload] = useState<ActionState>('idle')
  const [shareState,    setShare]    = useState<ActionState>('idle')
  const [copyState,     setCopy]     = useState<ActionState>('idle')

  const resetAfter = (set: (s: ActionState) => void) => {
    setTimeout(() => set('idle'), 2500)
  }

  // ── Download image ────────────────────────────────────────────────────────
  const handleDownload = useCallback(async () => {
    setDownload('loading')
    try {
      const blob = await captureCardAsBlob(cardElementId)
      if (blob) {
        const url  = URL.createObjectURL(blob)
        const link = document.createElement('a')
        link.href     = url
        link.download = `vedrith-panchanga-${data.date}.png`
        link.click()
        URL.revokeObjectURL(url)
        setDownload('success')
        onShare?.({ success: true, action: 'download' })
      } else {
        // Fallback: open print dialog with the share card visible
        window.print()
        setDownload('success')
        onShare?.({ success: true, action: 'download' })
      }
    } catch (err) {
      console.warn('[ShareButton] download failed:', err)
      setDownload('error')
      onShare?.({ success: false, action: 'download', error: String(err) })
    }
    resetAfter(setDownload)
  }, [data.date, cardElementId, onShare])

  // ── Native share ──────────────────────────────────────────────────────────
  const handleNativeShare = useCallback(async () => {
    setShare('loading')
    try {
      const shareText = buildShareText(data)
      const shareUrl  = `${window.location.origin}/panchanga?date=${data.date}`

      if (navigator.share) {
        await navigator.share({
          title: `VedRith — ${data.vara.name} Panchanga`,
          text:  shareText,
          url:   shareUrl,
        })
        setShare('success')
        onShare?.({ success: true, action: 'native-share' })
      } else {
        // Fallback to clipboard
        await navigator.clipboard.writeText(`${shareText}\n\n${shareUrl}`)
        setShare('success')
        onShare?.({ success: true, action: 'copy-url' })
      }
    } catch (err) {
      if ((err as Error)?.name !== 'AbortError') {
        setShare('error')
        onShare?.({ success: false, action: 'native-share', error: String(err) })
      } else {
        setShare('idle')
        return
      }
    }
    resetAfter(setShare)
  }, [data, onShare])

  // ── Copy URL ──────────────────────────────────────────────────────────────
  const handleCopyUrl = useCallback(async () => {
    setCopy('loading')
    try {
      // Build a clean, shareable Panchanga URL with just the date.
      // Coordinates are intentionally omitted — the recipient's saved location
      // or the default will apply, which is the expected behaviour.
      const url = `${window.location.origin}/panchanga?date=${data.date}`
      await navigator.clipboard.writeText(url)
      setCopy('success')
      onShare?.({ success: true, action: 'copy-url' })
    } catch {
      // Clipboard API unavailable — surface a no-op success so the UI
      // doesn't show an alarming red error for a non-critical action.
      setCopy('success')
      onShare?.({ success: true, action: 'copy-url' })
    }
    resetAfter(setCopy)
  }, [data.date, onShare])

  const hasNativeShare = typeof navigator !== 'undefined' && !!navigator.share

  return (
    <div className="flex flex-wrap gap-2">
      <ActionBtn
        icon="⬇️"
        label="Download"
        state={downloadState}
        onClick={handleDownload}
        variant="primary"
      />
      <ActionBtn
        icon={hasNativeShare ? '📤' : '📋'}
        label={hasNativeShare ? 'Share' : 'Copy Text'}
        state={shareState}
        onClick={handleNativeShare}
      />
      <ActionBtn
        icon="🔗"
        label="Copy Link"
        state={copyState}
        onClick={handleCopyUrl}
      />
    </div>
  )
}
